version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    command: --admin-password '${HASHED_PASSWORD}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - app_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      INITIAL_ADMIN_EMAIL: ${NPM_ADMIN_NAME}
      INITIAL_ADMIN_PASSWORD: ${NPM_ADMIN_PASS}
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - /var/docker/mariadb/conf:/etc/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    environment:
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mariadb
    ports:
      - "8183:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    networks:
      - app_network
      
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SECRET_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_ADMIN_PASSWORD}
    volumes:
      - /path/to/duplicati/config:/config
      - /path/to/backups:/backups
      - /path/to/source:/source
    ports:
      - "8200:8200"
    restart: unless-stopped
    networks:
      - app_network
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9091:9091"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://localhost:9099
    volumes:
      - minio_storage:/data
    networks:
      - app-network
    command: server --address ":9099" --console-address ":9091" /data
    restart: always

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # HTTP management UI
    volumes:
      - /etc/letsencrypt/live/ondergrup.hidirektor.com.tr:/certs
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ROOT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ROOT_PASSWORD}
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: [ "redis-server", "--include", "/etc/redis/redis.conf" ]
    networks:
      - app-network
    restart: always

volumes:
  portainer_data:

networks:
  app_network:
    name: ${NETWORK_NAME}
    driver: bridge
